name: Continous Integration
on:
  push:
    paths:
      - '**.dart'
      - 'pubspec.yaml'
  pull_request:
    branches: [ master, ]
    paths:
      - '**.dart'
      - 'pubspec.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.13.x'

      - run: dart --version
      - run: flutter --version

      - name: Install app dependencies
        run: flutter pub get

      - name: Test app
        run: flutter test --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
